# from: https://github.com/maguowei/awesome-stars/blob/master/.github/workflows/schedules.yml

name: update awesome-stars
on:
  workflow_dispatch:
  schedule:
    - cron: 30 0 * * *

jobs:
  awesome-stars:
    name: update awesome-stars
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade starred
          pip install github3.py==3.2.0

      - name: Update stars
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          starred --username sunlei --sort > README.md
          sed -i '1c# Awesome Stars' README.md

      - name: Commit stars record files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update stars"

          branch: master
          commit_options: "--no-verify --signoff"
          file_pattern: README.md
          repository: .

          commit_user_name: GitHub Actions Bot
          commit_user_email: actions@github.com
          commit_author: GitHub Actions Bot <actions@github.com>
